#pragma once

#include <stdint.h>

/* XXX: Comment out this line for a non-test network */
//#define GOP_TEST_NETWORK

#define GOP_TEST_NETWORK_VERSION                            83 // autogenerated

#define GOP_BLOCKCHAIN_DATABASE_VERSION                     uint64_t( 201 )

/**
 *  The address prepended to string representation of
 *  addresses.
 *
 *  Changing these parameters will result in a hard fork.
 */ 
#define GOP_ADDRESS_PREFIX                                  "GOP"
#define GOP_BLOCKCHAIN_SYMBOL                               "GOP"
#define GOP_BLOCKCHAIN_NAME                                 "GOPs"
#define GOP_BLOCKCHAIN_DESCRIPTION                          "The Future of Banking"
#define GOP_BLOCKCHAIN_PRECISION                            100000

#define GOP_BLOCKCHAIN_MAX_UIA_MARKET_FEE                   10000
#define GOP_BLOCKCHAIN_BLOCK_INTERVAL_SEC                   int64_t(10)
#define GOP_BLOCKCHAIN_BLOCKS_PER_HOUR                      ((60*60)/GOP_BLOCKCHAIN_BLOCK_INTERVAL_SEC)
#define GOP_BLOCKCHAIN_BLOCKS_PER_DAY                       (GOP_BLOCKCHAIN_BLOCKS_PER_HOUR*int64_t(24))
#define GOP_BLOCKCHAIN_BLOCKS_PER_YEAR                      (GOP_BLOCKCHAIN_BLOCKS_PER_DAY*int64_t(365))

#define GOP_BLOCKCHAIN_NUM_DELEGATES                        uint32_t(99)
#define GOP_MAX_DELEGATE_PAY_PER_BLOCK                      int64_t( 1 * GOP_BLOCKCHAIN_PRECISION ) // 50 XTS
#define GOP_BLOCKCHAIN_MAX_UNDO_HISTORY                     GOP_BLOCKCHAIN_BLOCKS_PER_HOUR

#define GOP_BLOCKCHAIN_MAX_SLATE_SIZE                       (GOP_BLOCKCHAIN_NUM_DELEGATES + (GOP_BLOCKCHAIN_NUM_DELEGATES/10))
#define GOP_BLOCKCHAIN_MAX_MESSAGE_SIZE                     2048
#define GOP_BLOCKCHAIN_MAX_FREE_MESSAGE_SIZE                1024
#define GOP_BLOCKCHAIN_MAX_SOFT_MAX_MESSAGE_SIZE            40
#define GOP_BLOCKCHAIN_MIN_MESSAGE_FEE_COE                  100
#define GOP_BLOCKCHAIN_MAX_TRANSACTION_EXPIRATION_SEC       (60*60*24*2)
#define GOP_BLOCKCHAIN_MAX_MEMO_SIZE                        19 // bytes
#define GOP_BLOCKCHAIN_EXTENDED_MEMO_SIZE                   32 // bytes
#define GOP_BLOCKCHAIN_MAX_EXTENDED_MEMO_SIZE               (GOP_BLOCKCHAIN_MAX_MEMO_SIZE + GOP_BLOCKCHAIN_EXTENDED_MEMO_SIZE)

/**
 *  The maximum amount that can be issued for user assets.
 *
 *  10^18 / 2^63 < 1  however, to support representing all share values as a double in
 *  languages like java script, we must stay within the epsilon so
 *
 *  10^15 / 2^53 < 1 allows all values to be represented as a double or an int64
 */
#define GOP_BLOCKCHAIN_MAX_SHARES                           (1000*1000*int64_t(1000)*1000*int64_t(1000))

#define GOP_BLOCKCHAIN_MIN_NAME_SIZE                        1
#define GOP_BLOCKCHAIN_MAX_NAME_SIZE                        63
#define GOP_BLOCKCHAIN_MAX_NAME_DATA_SIZE                   (1024*64)

#define GOP_BLOCKCHAIN_MAX_SUB_SYMBOL_SIZE                  8 // characters
#define GOP_BLOCKCHAIN_MIN_SYMBOL_SIZE                      3 // characters
#define GOP_BLOCKCHAIN_MAX_SYMBOL_SIZE                      12 // characters

#define GOP_BLOCKCHAIN_MIN_BURN_FEE                         GOP_BLOCKCHAIN_PRECISION * 1 // 1 XTS

#ifdef GOP_TEST_NETWORK
#define GOP_BLOCKCHAIN_VOTE_UPDATE_PERIOD_SEC               10
#else
#define GOP_BLOCKCHAIN_VOTE_UPDATE_PERIOD_SEC               (60*60) // 1 hour
#endif

#define GOP_BLOCKCHAIN_MIN_FEEDS                            ((GOP_BLOCKCHAIN_NUM_DELEGATES/2) + 1)
#define GOP_BLOCKCHAIN_MINIMUM_SHORT_ORDER_SIZE             (GOP_BLOCKCHAIN_PRECISION*100)
#define GOP_BLOCKCHAIN_MIN_YIELD_PERIOD_SEC                 (60*60*24) // 24 hours
#define GOP_BLOCKCHAIN_MAX_YIELD_PERIOD_SEC                 (GOP_BLOCKCHAIN_BLOCKS_PER_YEAR * GOP_BLOCKCHAIN_BLOCK_INTERVAL_SEC) // 1 year

#ifdef GOP_TEST_NETWORK
#define GOP_BLOCKCHAIN_MAX_SHORT_PERIOD_SEC                 (2*60*60) // 2 hours
#else
#define GOP_BLOCKCHAIN_MAX_SHORT_PERIOD_SEC                 (30*24*60*60) // 1 month
#endif
#define GOP_BLOCKCHAIN_MAX_SHORT_APR_PCT                    (uint64_t(50))

#define GOP_BLOCKCHAIN_MCALL_D2C_NUMERATOR                  1
#define GOP_BLOCKCHAIN_MCALL_D2C_DENOMINATOR                2

// TODO: This stuff only matters for propagation throttling; should go somewhere else
#define GOP_BLOCKCHAIN_DEFAULT_RELAY_FEE                    1000 // XTS
#define GOP_BLOCKCHAIN_MAX_TRX_PER_SECOND                   100  // (10)
#define GOP_BLOCKCHAIN_MAX_PENDING_QUEUE_SIZE               1000 // (GOP_BLOCKCHAIN_MAX_TRX_PER_SECOND * GOP_BLOCKCHAIN_BLOCK_INTERVAL_SEC)
